refactor(e2e_tests): fix linter warning due to chaining
As described here
https://docs.cypress.io/guides/core-concepts/retry-ability#Actions-should-be-at-the-end-of-chains-not-the-middle
actions should be at the end of chains in case the app re-renders due to
an intermediate action.

Fix:

    Error: 18:5  error  It is unsafe to chain further commands that
    rely on the subject after this command. It is best to split the
    chain, chaining again from `cy.` in a next command line
    cypress/unsafe-to-chain-command