GUI: Replace logo.png with logo.svg (after svgo optimization) (#78)
The logo.svg as exported by Inkscape was not usable. The following error
appeared when running 'npm start'.

    SyntaxError: unknown: Namespace tags are not supported by default.
    React's JSX doesn't support namespace tags. You can set
    `throwIfNamespace: false` to bypass this warning.

Discussion of the issue:
https://github.com/facebook/create-react-app/issues/11770

To fix it:

    npm install --saveDev svgo
    ./node_modules/svgo/bin/svgo src/logo.svg